# Generated by Django 3.2.12 on 2024-05-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_name_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(blank=True, default='Normal', max_length=100, null=True),
        ),
    ]
