# Generated by Django 3.2.12 on 2024-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(blank=True, default='Public', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(default='disconnected', max_length=10),
        ),
    ]
